[build]
  command = "npm run build"
  publish = "build"
  
[context.production]
  environment = { PUBLIC_SUPABASE_URL = "https://kxmwcpeuiklblpehddkz.supabase.co", PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4bXdjcGV1aWtsYmxwZWhkZGt6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczODk4ODE2MSwiZXhwIjoyMDU0NTY0MTYxfQ.vE_95TXJ_JdLvVvFBw1EgIhjzASjiYuKPDCAOVRMe80" }

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "build"
  autoLaunch = true
  framework = "#custom"
